version: '3.8'

services:
  nginx:
    platform: linux/amd64
    image: nginx:1.21-alpine
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./php:/var/www/html
    networks:
      - frontend
      - backend

  php:
    platform: linux/amd64
    image: php:7.4-fpm-alpine
    container_name: php
    volumes:
      - ./php:/var/www/html
    networks:
      - backend

  mysql:
    platform: linux/amd64
    image: mysql:5.7.35
    container_name: mysql
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
    secrets:
      - mysql_root_password
      - mysql_password
    networks:
      - backend

  phpmyadmin:
    platform: linux/amd64
    image: phpmyadmin/phpmyadmin:5.1.1
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
    networks:
      - backend

secrets:
  mysql_root_password:
    file: ./secrets/mysql_root_password.txt
  mysql_password:
    file: ./secrets/mysql_password.txt

networks:
  frontend:
  backend:
